name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'  # Esto ejecutará la acción para cualquier push de una etiqueta que siga el patrón vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest ${{ secrets.DOCKER_USERNAME }}/your-image-name:${GITHUB_REF##*/v}
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${GITHUB_REF##*/v}
